# Generated by Django 3.2.4 on 2021-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('des', 'all'), ('dev', 'featured'), ('gra', 'Remix')], default='des', max_length=4),
            preserve_default=False,
        ),
    ]
