# Generated by Django 3.2.4 on 2021-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_skill_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='github', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
