# Generated by Django 3.2.4 on 2021-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('des', 'Men'), ('dev', 'Women'), ('gra', 'Tech & stuff')], max_length=4),
        ),
    ]
